name: PR Title Check

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    name: Check PR title format
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    
    steps:
        - uses: amann/action-sematic-pull-request@v6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            types: |
              feat
              fix
              chore
              docs
              test
              refactor
            requireScope: true
